# Site settings
title: Nicolas Schneider - Data Scientist / Developer
email: schneidernicolas90@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Data Scientist and ML Engineer specializing in LLM integration, computer vision, and optimization algorithms. 
  I build production-ready ML systems that bridge research and real-world applications, with expertise in 
  PyTorch, transformers, and multimodal data processing.
baseurl: "" # the subpath of your site is empty for a user site (username.github.io)
url: "https://nicolas2912.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Nicolas2912 # optional

# SEO and Social Media
author: Nicolas Schneider
twitter:
  username: # Add your Twitter handle if you have one
  card: summary_large_image

# Open Graph / Social Media defaults
social:
  name: Nicolas Schneider
  links:
    - https://github.com/Nicolas2912
    - https://www.linkedin.com/in/nicolas-schneider1/

# Default image for social sharing (add this image to your images folder)
logo: /images/profile.jpg
social_image: /images/profile.jpg

# SEO plugin settings
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Additional SEO settings
lang: en_US
timezone: Europe/Berlin

# Build settings
theme: minima # A simple default Jekyll theme
# Plugins
plugins:
  - jekyll-feed # Generates an Atom feed for your blog

# Enable syntax highlighting for code blocks using Rouge
markdown: kramdown
highlighter: rouge

# Kramdown settings for GitHub Flavored Markdown and Rouge syntax highlighting
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
  math_engine: mathjax
  math_engine_opts:
    tex: {}

# Collections for Projects
collections:
  projects:
    output: true # Tells Jekyll to create a page for each project file
    permalink: /projects/:name/ # Sets the URL structure for project pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be re-included by adding them to the `include:` list of the Jekyll config file.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
